# fly.toml app configuration file generated for throbbing-grass-290 on 2023-10-14T09:50:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "throbbing-grass-290"
primary_region = "otp"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
