defmodule JeffWeb.Router do
  use Plug.Router

  plug Plug.Parsers, parsers: [:urlencoded]
  plug Plug.Logger
  plug :match
  plug :dispatch

  defp slicer_args do
    %{
      acceleration_enabled: "false",
      acceleration_infill: "machine_acceleration",
      acceleration_ironing: "0",
      acceleration_prime_tower: "250",
      acceleration_print_layer_0: "3000",
      acceleration_print: "500",
      acceleration_roofing: "1000",
      acceleration_skirt_brim: "500",
      acceleration_support_bottom: "machine_acceleration",
      acceleration_support_infill: "machine_acceleration",
      acceleration_support_roof: "machine_acceleration",
      acceleration_topbottom: "750",
      acceleration_travel_layer_0: "1000",
      acceleration_travel: "500",
      acceleration_wall_0: "acceleration_wall",
      acceleration_wall_x: "machine_acceleration",
      adaptive_layer_height_enabled: "false",
      adaptive_layer_height_variation_step: "0.04",
      adaptive_layer_height_variation: "0.04",
      adhesion_type: "skirt",
      alternate_extra_perimeter: "false",
      anti_overhang_mesh: "false",
      bottom_layers: "3",
      bottom_skin_expand_distance: "1.2",
      bottom_skin_preshrink: "1.2",
      bridge_fan_speed_2: "0",
      bridge_fan_speed_3: "cool_fan_speed_min",
      bridge_fan_speed: "100",
      bridge_settings_enabled: "false",
      bridge_skin_material_flow_2: "skin_material_flow",
      bridge_skin_material_flow_3: "skin_material_flow",
      bridge_skin_material_flow: "skin_material_flow",
      bridge_skin_speed_2: "speed_topbottom",
      bridge_skin_speed_3: "speed_topbottom",
      bridge_skin_speed: "speed_topbottom",
      bridge_wall_coast: "100",
      bridge_wall_material_flow: "wall_material_flow",
      bridge_wall_min_length: "5",
      bridge_wall_speed: "bridge_skin_speed",
      brim_inside_margin: "0",
      brim_replaces_support: "false",
      brim_smart_ordering: "true",
      carve_multiple_volumes: "false",
      center_object: "false",
      clean_between_layers: "false",
      conical_overhang_enabled: "false",
      connect_infill_polygons: "true",
      cool_fan_enabled: "true",
      cool_fan_full_at_height: "layer_height_0 + 2 * layer_height",
      cool_fan_full_layer: "2",
      cool_fan_speed_0: "0",
      cool_fan_speed_max: "100",
      cool_fan_speed_min: "100",
      cool_min_layer_time_fan_speed_max: "10",
      cool_min_layer_time: "10",
      cool_min_speed: "10",
      cool_min_temperature: "0",
      cross_infill_pocket_size: "2.0",
      cutting_mesh: "false",
      draft_shield_enabled: "false",
      fill_outline_gaps: "false",
      gantry_height: "25",
      gradual_infill_step_height: "0",
      gradual_infill_steps: "0",
      gradual_support_infill_step_height: "0.2",
      gradual_support_infill_steps: "0",
      hole_xy_offset_max_diameter: "0",
      hole_xy_offset: "0.2",
      infill_angles: "[]",
      infill_before_walls: "false",
      infill_enable_travel_optimization: "false",
      infill_extruder_nr: "0",
      infill_line_distance: "0.4",
      infill_line_width: "0.6",
      infill_material_flow: "100",
      infill_mesh_order: "0",
      infill_mesh: "false",
      infill_multiplier: "1",
      infill_offset_x: "0",
      infill_offset_y: "0",
      infill_overlap_mm: "0.06",
      infill_overlap: "30.0",
      infill_pattern: "cubic",
      infill_randomize_start_location: "false",
      infill_sparse_thickness: "0.2",
      infill_support_enabled: "false",
      infill_wall_line_count: "0",
      infill_wipe_dist: "0.0",
      initial_bottom_layers: "2",
      initial_layer_line_width_factor: "110",
      inset_direction: "inside_out",
      interlocking_enable: "false",
      ironing_enabled: "false",
      ironing_flow: "0",
      ironing_line_spacing: "0",
      ironing_only_highest_layer: "false",
      jerk_enabled: "false",
      jerk_infill: "jerk_print",
      jerk_ironing: "0",
      jerk_prime_tower: "5",
      jerk_print_layer_0: "20",
      jerk_print: "8",
      jerk_roofing: "jerk_print",
      jerk_skirt_brim: "5",
      jerk_support_bottom: "5",
      jerk_support_infill: "jerk_print",
      jerk_support_roof: "5",
      jerk_topbottom: "jerk_print",
      jerk_travel_layer_0: "jerk_travel",
      jerk_travel: "jerk_print",
      jerk_wall_0: "jerk_wall",
      jerk_wall_x: "jerk_print",
      layer_height_0: "0.3",
      layer_height: "0.1",
      layer_start_x: "0.0",
      layer_start_y: "0.0",
      machine_acceleration: "500",
      machine_always_write_active_tool: "false",
      machine_center_is_zero: "false",
      machine_depth: "235",
      machine_disallowed_areas: "[]",
      machine_end_gcode: "G91 ;Relative positioning\nG1 E-2 F2700 ;Retract a bit\nG1 E-2 Z0.2 F2400 ;Retract and raise Z\nG1 X5 Y5 F3000 ;Wipe out\nG1 Z10 ;Raise Z more\nG90 ;Absolute positioning\n\nG1 X0 Y{machine_depth} ;Present print\nM106 S0 ;Turn-off fan\nM104 S0 ;Turn-off hotend\nM140 S0 ;Turn-off bed\n\nM84 X Y E ;Disable all steppers but Z\n",
      machine_extruder_cooling_fan_number: "0",
      machine_extruder_start_code: "",
      machine_extruders_share_heater: "false",
      machine_extruders_share_nozzle: "false",
      machine_firmware_retract: "false",
      machine_gcode_flavor: "RepRap (Marlin/Sprinter)",
      machine_heated_bed: "true",
      machine_heated_build_volume: "false",
      machine_height: "250",
      machine_max_acceleration_e: "5000",
      machine_max_acceleration_x: "500",
      machine_max_acceleration_y: "500",
      machine_max_acceleration_z: "100",
      machine_max_feedrate_e: "50",
      machine_max_feedrate_x: "500",
      machine_max_feedrate_y: "500",
      machine_max_feedrate_z: "10",
      machine_max_jerk_e: "5",
      machine_max_jerk_xy: "10",
      machine_max_jerk_z: "0.4",
      machine_minimum_feedrate: "false",
      machine_name: "Creality Ender-3",
      machine_nozzle_offset_x: "0",
      machine_nozzle_offset_y: "0",
      machine_nozzle_size: "0.4",
      machine_nozzle_temp_enabled: "true",
      machine_nozzle_tip_outer_diameter: "1",
      machine_shape: "rectangular",
      machine_start_gcode: "; Ender 3 Custom Start G-code\nG92 E0 ; Reset Extruder\nG28 ; Home all axes\nG1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed\nG1 X0.1 Y20 Z0.3 F5000.0 ; Move to start position\nG1 X0.1 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line\nG1 X0.4 Y200.0 Z0.3 F5000.0 ; Move to side a little\nG1 X0.4 Y20 Z0.3 F1500.0 E30 ; Draw the second line\nG92 E0 ; Reset Extruder\nG1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed\nG1 X5 Y20 Z0.3 F5000.0 ; Move over to prevent blob squish",
      machine_use_extruder_offset_to_offset_coords: "true",
      machine_width: "235",
      magic_fuzzy_skin_enabled: "false",
      magic_mesh_surface_mode: "\"surface\" if simple_mode else \"normal\"",
      magic_spiralize: "false",
      material_alternate_walls: "false",
      material_bed_temp_prepend: true,
      material_bed_temp_wait: "true",
      material_bed_temperature_layer_0: "60",
      material_diameter: "1.75",
      material_final_print_temperature: "material_print_temperature",
      material_flow_layer_0: "100",
      material_guid: "",
      material_initial_print_temperature: "material_print_temperature",
      material_print_temp_prepend: "true",
      material_print_temp_wait: "true",
      material_print_temperature_layer_0: "215",
      material_shrinkage_percentage_xy: "100.0",
      material_shrinkage_percentage_z: "100.0",
      max_extrusion_before_wipe: "10",
      mesh_position_x: "0",
      mesh_position_y: "0",
      mesh_position_z: "0",
      mesh_rotation_matrix: "[[1,0,0], [0,1,0], [0,0,1]]",
      meshfix_extensive_stitching: "false",
      meshfix_keep_open_polygons: "false",
      meshfix_maximum_deviation: "layer_height / 2",
      meshfix_maximum_extrusion_area_deviation: "0.01",
      meshfix_maximum_resolution: "0.25",
      meshfix_maximum_travel_resolution: "meshfix_maximum_resolution",
      meshfix_union_all_remove_holes: "false",
      meshfix_union_all: "true",
      min_bead_width: "0",
      min_even_wall_line_width: "0.34",
      min_feature_size: "0",
      min_infill_area: "0.1",
      min_odd_wall_line_width: "0.34",
      min_skin_width_for_expansion: "2",
      min_wall_line_width: "0.3",
      minimum_interface_area: "10",
      minimum_polygon_circumference: "0.2",
      minimum_roof_area: "0",
      minimum_support_area: "2 if support_structure == 'normal' else 0",
      mold_enabled: "false",
      ooze_shield_enabled: "false",
      optimize_wall_printing_order: "True",
      prime_blob_enable: "false",
      prime_tower_brim_enable: "false",
      prime_tower_enable: "false",
      prime_tower_flow: "100",
      prime_tower_line_width: "0.48",
      raft_base_acceleration: "machine_acceleration",
      raft_base_extruder_nr: "0",
      raft_base_jerk: "10",
      raft_base_line_width: "1.0",
      raft_base_speed: "20",
      raft_base_thickness: "0.3",
      raft_interface_acceleration: "machine_acceleration",
      raft_interface_extruder_nr: "0",
      raft_interface_jerk: "25",
      raft_interface_line_width: "0.4",
      raft_interface_speed: "40",
      raft_interface_thickness: "0.2",
      raft_surface_acceleration: "machine_acceleration",
      raft_surface_extruder_nr: "0",
      raft_surface_jerk: "speed_print",
      raft_surface_line_width: "0.4",
      raft_surface_speed: "40",
      raft_surface_thickness: "0.1",
      relative_extrusion: "false",
      remove_empty_first_layers: "true",
      retraction_amount: "6.5",
      retraction_combing_max_distance: "30",
      retraction_combing: "'off' if retraction_hop_enabled else 'noskin'",
      retraction_count_max: "100",
      retraction_enable: "true",
      retraction_extra_prime_amount: "0",
      retraction_extrusion_window: "10",
      retraction_hop_after_extruder_switch_height: "1",
      retraction_hop_after_extruder_switch: "true",
      retraction_hop_enabled: "false",
      retraction_hop_only_when_collides: "false",
      retraction_hop: "0.2",
      retraction_min_travel: "1.5",
      retraction_prime_speed: "0.8",
      retraction_retract_speed: "0.8",
      retraction_speed: "0.8",
      roofing_angles: "[]",
      roofing_extruder_nr: "-1",
      roofing_layer_count: "0",
      roofing_line_width: "line_width * 0.75",
      roofing_material_flow: "material_flow",
      roofing_monotonic: "true",
      skin_angles: "[]",
      skin_edge_support_layers: "4",
      skin_line_width: "0.4",
      skin_material_flow_layer_0: "100",
      skin_material_flow: "100",
      skin_no_small_gaps_heuristic: "true",
      skin_overlap_mm: "0.06",
      skin_overlap: "10.0",
      skirt_brim_extruder_nr: "false",
      skirt_brim_line_width: "0.5",
      skirt_brim_material_flow: "100",
      skirt_brim_minimal_length: "50",
      skirt_brim_speed: "5",
      skirt_gap: "10.0",
      skirt_height: "3",
      skirt_line_count: "3",
      slicing_tolerance: "middle",
      small_feature_max_length: "0",
      small_feature_speed_factor: "50",
      speed_equalize_flow_width_factor: "100.0",
      speed_infill: "speed_print",
      speed_ironing: "0",
      speed_layer_0: "20.0",
      speed_prime_tower: "speed_topbottom",
      speed_print_layer_0: "30",
      speed_print: "50.0",
      speed_roofing: "speed_topbottom",
      speed_slowdown_layers: "1",
      speed_support_bottom: "30",
      speed_support_infill: "45",
      speed_support_interface: "speed_topbottom",
      speed_support_roof: "30",
      speed_support: "speed_wall_0",
      speed_topbottom: "speed_print",
      speed_travel_layer_0: "100 if speed_layer_0 < 20 else 150 if speed_layer_0 > 30 else speed_layer_0 * 5",
      speed_travel: "150.0 if speed_print < 60 else 250.0 if speed_print > 100 else speed_print * 2.5",
      speed_wall_0: "speed_wall",
      speed_wall_x: "speed_wall",
      speed_z_hop: "5",
      support_angle: "math.floor(math.degrees(math.atan(line_width / 2.0 /layer_height)))",
      support_bottom_angles: "[]",
      support_bottom_distance: "0.2",
      support_bottom_enable: "false",
      support_bottom_extruder_nr: "0",
      support_bottom_line_width: "0.4",
      support_bottom_material_flow: "100",
      support_bottom_pattern: "concentric",
      support_bottom_stair_step_height: "0.2",
      support_bottom_stair_step_min_slope: "0",
      support_bottom_stair_step_width: "0",
      support_brim_enable: "true",
      support_brim_line_count: "5",
      support_brim_width: "4",
      support_conical_angle: "0",
      support_conical_enabled: "false",
      support_connect_zigzags: "true",
      support_enable: "true",
      support_extruder_nr_layer_0: "0",
      support_infill_angles: "[]",
      support_infill_extruder_nr: "0",
      support_infill_rate: "0 if support_enable and support_structure == 'tree' else 20",
      support_infill_sparse_thickness: "0.2",
      support_interface_density: "33.333",
      support_interface_enable: "true",
      support_interface_height: "layer_height * 4",
      support_interface_pattern: "'grid'",
      support_interface_skip_height: "0.2",
      support_join_distance: "0",
      support_line_distance: "2.66",
      support_line_width: "0.6",
      support_material_flow: "material_flow * 0.95",
      support_mesh: "false",
      support_offset: "0.8",
      support_pattern: "'zigzag'",
      support_roof_angles: "[]",
      support_roof_enable: "true",
      support_roof_extruder_nr: "0",
      support_roof_height: "0.4",
      support_roof_line_distance: "0.4",
      support_roof_line_width: "0.35",
      support_roof_material_flow: "100",
      support_roof_offset: "0",
      support_roof_pattern: "concentric",
      support_roof_wall_count: "0",
      support_skip_some_zags: "false",
      support_structure: "normal",
      support_top_distance: "0.1",
      support_tower_maximum_supported_diameter: "0",
      support_type: "everywhere",
      support_use_towers: "false",
      support_wall_count: "0",
      support_xy_distance_overhang: "wall_line_width_0",
      support_xy_distance: "wall_line_width_0 * 2",
      support_xy_overrides_z: "'xy_overrides_z'",
      support_z_distance: "layer_height if layer_height >= 0.16 else layer_height * 2",
      support_zag_skip_count: "5",
      switch_extruder_extra_prime_amount: "0",
      switch_extruder_prime_speed: "20",
      switch_extruder_retraction_amount: "20",
      switch_extruder_retraction_speed: "20",
      top_bottom_extruder_nr: "0",
      top_bottom_thickness: "layer_height_0 + layer_height * 3",
      top_layers: "5",
      top_skin_expand_distance: "1.2",
      top_skin_preshrink: "1.2",
      travel_avoid_distance: "1",
      travel_avoid_other_parts: "true",
      travel_avoid_supports: "true",
      travel_retract_before_outer_wall: "true",
      wall_0_extruder_nr: "0",
      wall_0_inset: "0",
      wall_0_material_flow_layer_0: "material_flow_layer_0",
      wall_0_material_flow: "material_flow_layer_0",
      wall_0_wipe_dist: "0.0",
      wall_distribution_count: "2",
      wall_line_count: "3",
      wall_line_width_0: "line_width-0.05",
      wall_line_width_x: "0.4",
      wall_overhang_angle: "90",
      wall_overhang_speed_factor: "100",
      wall_thickness: "line_width * 2",
      wall_transition_angle: "10",
      wall_transition_filter_deviation: "0.15",
      wall_transition_filter_distance: "1",
      wall_transition_length: "1",
      wall_x_extruder_nr: "0",
      wall_x_material_flow_layer_0: "material_flow_layer_0",
      wall_x_material_flow: "material_flow_layer_0",
      wipe_brush_pos_x: "100",
      wipe_hop_amount: "1",
      wipe_hop_enable: "true",
      wipe_hop_speed: "10",
      wipe_move_distance: "20",
      wipe_pause: "0",
      wipe_repeat_count: "5",
      wipe_retraction_amount: "1",
      wipe_retraction_enable: "true",
      wipe_retraction_extra_prime_amount: "0",
      wipe_retraction_prime_speed: "3",
      wipe_retraction_retract_speed: "3",
      xy_offset_layer_0: "0",
      xy_offset: "0",
      z_seam_corner: "'z_seam_corner_weighted'",
      z_seam_relative: "false",
      z_seam_type: "'back'",
      z_seam_x: "100.0",
      z_seam_y: "100.0",
      zig_zaggify_infill: "false",
      zig_zaggify_support: "false",
    }
  end

  get "/slice" do
    %{"stl" => stl_url} = conn.query_params
    sha256 = :crypto.hash(:sha256, stl_url) |> Base.encode16(case: :lower)
    tmp_stl = Path.join(System.tmp_dir!(), "#{sha256}.stl")
    tmp_gcode = Path.join(System.tmp_dir!(), "#{sha256}.gcode")

    if not File.exists?(tmp_stl) do
      :httpc.request(:get, {stl_url, []}, [], stream: to_charlist(tmp_stl))
    end

    {out, status} =
      System.cmd(
        "CuraEngine",
        ["slice" | Enum.flat_map(slicer_args(), &["-s", "#{elem(&1, 0)}=#{elem(&1, 1)}"])] ++
          ["-e0", "-l", tmp_stl, "-o", tmp_gcode],
        stderr_to_stdout: true
      )

    if status == 0 do
      send_file(conn, 200, tmp_gcode)
    else
      send_resp(conn, 500, out)
    end
  end

  match _ do
    send_resp(conn, 404, "not found")
  end
end
